name: Law assist AI law linking development

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:

  dev-container-build-push:
    runs-on: [self-hosted, deployment]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Copy models to runner
      run: |
        cp /home/la-2025/models/Classification_model/model.safetensors models/Classification_model/
        cp /home/la-2025/models/ner_model/model.safetensors models/ner_model/
        mkdir models/STS_model
        mkdir models/STS_model_V2
        cp /home/la-2025/models/STS_model/bert-sts-similarity.pt models/STS_model/
        cp /home/la-2025/models/STS_model_V2/bert-sts-V2.pt models/STS_model_V2/

    - name: Check source code in runner
      run: "ls models -a -R"
